### ISSUE TITLE
README does not really explain, what this plugin does

### ISSUE THREAD

**Issue by jounathaen** [ncm2/ncm2-neoinclude#2]
The README only states, that it is based on neoinclude, which in turn only explains that it is a "Include completion framework". I still don't know what this plugin does and why I should install it.

A short example in the README could help.

**Comment by jsfaint** [comment]
neoinclude provides `include` completion for neocomplete, deoplete, and ncm1

For C, when you type `#include <`, it will show the header file candidates.
For Python, when you type `import xx`, it will show the import candidates.
neoinclude also supports some other languages.

This plugin is a wrap for neoinclude to support ncm2.

**Comment by jounathaen** [comment]
Thanks!
This is a good explanation. I'd suggest to put it in the README.

**Comment by jsfaint** [comment]
Updated. Thanks for your advice.
